[[ -o interactive ]] || return

command -v kubectl >/dev/null 2>&1 || return

# `k` is the alias this setup guarantees everywhere kubectl exists — server and
# both Macs. See docs/terminal-and-editor-defaults.md.
#
# Unlike the ls/cat aliases in 50_aliases.sh this shadows nothing: `k` is not a
# real command, so there is no incompatible-flag trap of the kind that keeps
# find/grep un-aliased.
alias k=kubectl

# kubectl's zsh completion is generated by the binary, and generating it costs
# ~200ms of shell startup — the same cost 50_completion.sh caches away for
# compinit. Cache it too, and regenerate only when the kubectl binary is newer
# than the cache (i.e. after an upgrade).
#
# This runs after 50_completion.sh (same numeric tier, sorted alphabetically),
# so compinit has already defined compdef by the time we get here.
_kubectl_comp="${ZDOTDIR:-$HOME}/.zcompcache-kubectl"
if [[ ! -s "$_kubectl_comp" || "$(command -v kubectl)" -nt "$_kubectl_comp" ]]; then
  kubectl completion zsh >| "$_kubectl_comp" 2>/dev/null
fi
[[ -s "$_kubectl_comp" ]] && source "$_kubectl_comp"
unset _kubectl_comp

# Completion for the alias. zsh resolves `k=kubectl` to kubectl's own completer,
# so `k get po<TAB>` behaves exactly like `kubectl get po<TAB>`.
(( $+functions[_kubectl] )) && compdef k=kubectl

# krew-installed plugins are invoked as `kubectl <plugin>`; kubectl finds them
# on PATH (see 40_path.sh, which adds ~/.krew/bin unguarded so scripts get them
# too). Nothing else is needed to wire krew up.
